# Generated by Django 4.2.5 on 2025-01-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='goal',
        ),
    ]
